In [105]:
import pandas as pd

# To DataFrame type

In [106]:
def load_data(file_name):
    file = open(file_name, "r")
    file_string = file.read()
    file_string_list = file_string.split("\x00\n")
    for i in range(len(file_string_list)):
        file_string_list[i] = file_string_list[i].split(",").copy()
    return file_string_list[:-1]

In [107]:
def convert2df(string_list, col_name=None):
    df = pd.DataFrame(string_list)
    if col_name is not None:
        df.columns = col_name
    df = df.astype(int)
    return df

In [108]:
col_name = ("roll", "pitch", "yaw", "acc_x", "acc_y", "acc_z", "label")

In [109]:
train = load_data("dataset/train.txt")
df_train = convert2df(train, col_name)
display(df_train[df_train["label"]==0].describe()) #display move
display(df_train[df_train["label"]==1].describe()) #display idle

,roll,pitch,yaw,acc_x,acc_y,acc_z,label
count,145.000000,145.000000,145.000000,145.000000,145.000000,145.000000,145.0
mean,4472.275862,-8164.413793,3529.931034,-541.751724,699.068966,-0.972414,0.0
std,24571.220257,36767.871408,12547.137262,237.692218,239.803005,311.820660,0.0
min,-50820.000000,-88060.000000,-38780.000000,-1043.000000,-17.000000,-367.000000,0.0
25%,-13020.000000,-38780.000000,-3220.000000,-677.000000,675.000000,-168.000000,0.0
50%,5670.000000,-3430.000000,2940.000000,-621.000000,742.000000,-88.000000,0.0
75%,21210.000000,17500.000000,10990.000000,-419.000000,821.000000,59.000000,0.0
max,56350.000000,68950.000000,48300.000000,380.000000,1025.000000,1004.000000,0.0

,roll,pitch,yaw,acc_x,acc_y,acc_z,label
count,457.000000,457.000000,457.000000,457.000000,457.000000,457.000000,457.0
mean,456.148796,-603.194748,348.621444,64.236324,80.155361,826.153173,1.0
std,2082.726063,5386.224741,2003.424717,291.531770,284.595388,370.777151,0.0
min,-22820.000000,-6020.000000,-5040.000000,-1002.000000,-78.000000,3.000000,1.0
25%,-560.000000,-2100.000000,-1050.000000,12.000000,-13.000000,990.000000,1.0
50%,280.000000,-840.000000,280.000000,16.000000,-7.000000,996.000000,1.0
75%,1680.000000,70.000000,1190.000000,21.000000,0.000000,1000.000000,1.0
max,5180.000000,108220.000000,22540.000000,1027.000000,1008.000000,1024.000000,1.0

In [110]:
test_idle = load_data("dataset/test_idle.txt")
df_test_idle = convert2df(test_move, col_name)
df_test_idle["label"].values[:] = 1
display(df_test_idle.mean())

roll     11720.563380
pitch      609.295775
yaw      -1195.915493
acc_x     -558.816901
acc_y     -626.042254
acc_z      323.704225
label        1.000000
dtype: float64

In [111]:
test_move = load_data("dataset/test_move.txt")
df_test_move = convert2df(test_move, col_name)
df_test_move["label"].values[:] = 0
display(df_test_move.mean())

roll     11720.563380
pitch      609.295775
yaw      -1195.915493
acc_x     -558.816901
acc_y     -626.042254
acc_z      323.704225
label        0.000000
dtype: float64

In [112]:
df = df_train
df.append(df_test_idle)
df.append(df_test_move)
df.head()

   roll  pitch   yaw  acc_x  acc_y  acc_z  label
0   280   1820  1190     11      1    994      1
1  1190     70  1190     10     -8   1001      1
2  -140  -2520  -560      4     -9   1005      1
3  -140    910  3430     14     -8    992      1
4  2100  -4760   280     20      2   1024      1

In [113]:
df.to_csv("dataset.csv", index=False)